services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: aml-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sanctions_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sanctions_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: aml-ollama
    ports:
      - "11434:11434"